version: '3.7'

services:
  brymonsoft-messenger-rest-api:
    container_name: rest-api
    image: node:current
    build: ./
    command: npm run dev
    working_dir: /brymonsoft-messenger-rest-api
    ports:
      - '5000:5000'
    volumes:
      - ./:/brymonsoft-messenger-rest-api
